# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modbussy < Formula
  desc "Access modbus networks from the command line"
  homepage "https://hochgatterer.me"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3d635e7d9b6bb57e45ccf7f6b8e052899ce9fd904ad4a3f95db0f90d67abe817"

      def install
        bin.install "modbussy"
      end
    end
    on_arm do
      url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "679278420a4741f83e1abe501d9c923ab70f10f5207dd3311d16beead3c11452"

      def install
        bin.install "modbussy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "c429c50b8369bbbbb49dfc240bc8963807fe354a8d8c66ad094f689d08f9e722"

        def install
          bin.install "modbussy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "17cf49f91e0f34f043378b67fbb1a77a0c478db86cfa52f3a90bd2c61595c52b"

        def install
          bin.install "modbussy"
        end
      end
    end
  end
end
