# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modbussy < Formula
  desc "Access modbus networks from the command line"
  homepage "https://hochgatterer.me"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "fbaceefd104af2bb9343cd636c01bbb6b3e915932e2288c9c9da00e192fa3e68"

      def install
        bin.install "modbussy"
      end
    end
    on_arm do
      url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "8e9adc8747b5c6177d102948e56ced2908d9948d98c27087614e4516fc86f0b4"

      def install
        bin.install "modbussy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "e6eb5dc353e402acc1ae9c9429062a0c2cff375155d6f2c5472322edd568271f"

        def install
          bin.install "modbussy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brutella/modbussy/releases/download/1.0.0-beta1/modbussy_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "d3d6896ed48208f8daa42e08bbae0424e8021e486ea50c89367262be86bb9d89"

        def install
          bin.install "modbussy"
        end
      end
    end
  end
end
